server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: api-estagiario
          uri: lb://api-estagiario
          predicates:
            Path=/v1/**
          filters:
            - AuthFilter
        - id: auth
          uri: lb://auth
          predicates:
            Path=/Login