version: '3.1'
services:
  api_estagiarios:
    build: ../API-Estagiarios
    image: api_estagiarios/v1
    ports:
      - '8081:8081'
    depends_on:
      - db
      - eureka
  db:
    image: mysql
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ../../mysqlVolume:/var/lib/mysql
  eureka:
    build: ../DiscoveryServer
    image: eureka/v1
    ports:
    - '8761:8761'
  auth:
    build: ../auth
    image: auth/v1
    ports:
      - '8085:8085'
    depends_on:
      - db
      - eureka
  gateway:
    build: ../gateway
    image: gateway/v1
    ports:
      - '8080:8080'
    depends_on:
      - api_estagiarios
